const images = {
    logo: require('../image/logo-mona-furniture-12.png'),
    logokory2: require('../image/logokory2.jpg'),
    logokory: require('../image/logokory.jpg'),
    logokoryAdmin: require('../image/logokoryadmin.png'),
    banner1: require('../image/banner1.jpg'),
    banner2: require('../image/banner2.jpg'),
    banner3: require('../image/banner3.jpg'),
    banner21: require('../image/banner2-1.jpg'),
    banner22: require('../image/banner2-2.jpg'),
    banner23: require('../image/banner2-3.jpg'),
    banner31: require('../image/banner3-1.jpg'),
    banner3intro: require('../image/banner3intro.png'),
    introdiamond: require('../image/diamond.png'),
    intronetwork: require('../image/network.png'),
    introeye: require('../image/eye.png'),
    news01: require('../image/news01.jpg'),
    news02: require('../image/news02.jpg'),
    news03: require('../image/news03.jpg'),
    news04: require('../image/news04.jpg'),
    news05: require('../image/news05.jpg'),
    news06: require('../image/news06.jpg'),
    userAdmin1: require('../image/imgAdminUser1.png'),
    userAdmin2: require('../image/imgAdminUser2.png'),
    userAdmin3: require('../image/imgAdminUser3.png'),
};
export default images;
